export const statesBr = [
        { initials: 'AC', state: 'Acre' },
        { initials: 'AL', state: 'Alagoas' },
        { initials: 'AP', state: 'Amapá' },
        { initials: 'AM', state: 'Amazonas' },
        { initials: 'BA', state: 'Bahia' },
        { initials: 'CE', state: 'Ceará' },
        { initials: 'DF', state: 'Distrito Federal' },
        { initials: 'ES', state: 'Espírito Santo' },
        { initials: 'GO', state: 'Goías' },
        { initials: 'MA', state: 'Maranhão' },
        { initials: 'MT', state: 'Mato Grosso' },
        { initials: 'MS', state: 'Mato Grosso do Sul' },
        { initials: 'MG', state: 'Minas Gerais' },
        { initials: 'PA', state: 'Pará' },
        { initials: 'PB', state: 'Paraíba' },
        { initials: 'PR', state: 'Paraná' },
        { initials: 'PE', state: 'Pernambuco' },
        { initials: 'PI', state: 'Piauí' },
        { initials: 'RJ', state: 'Rio de Janeiro' },
        { initials: 'RN', state: 'Rio Grande do Norte' },
        { initials: 'RS', state: 'Rio Grande do Sul' },
        { initials: 'RO', state: 'Rondônia' },
        { initials: 'RR', state: 'Roraíma' },
        { initials: 'SC', state: 'Santa Catarina' },
        { initials: 'SP', state: 'São Paulo' },
        { initials: 'SE', state: 'Sergipe' },
        { initials: 'TO', state: 'Tocantins' }
];
